//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLevel
    {
        public int colLevelId { get; set; }
        public string colLevelName { get; set; }
        public string colLevelShortName { get; set; }
        public string colLevelDescription { get; set; }
        public string colChineseLevelName { get; set; }
        public string colThaiLevelName { get; set; }
        public string colTamilLevelName { get; set; }
        public string colKoreanLevelName { get; set; }
    }
}
