//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSyllabu
    {
        public int colSyllabusId { get; set; }
        public string colSyllabusName { get; set; }
        public Nullable<int> colTradeId { get; set; }
        public Nullable<int> colLevelId { get; set; }
        public string colSyllabusDocUrl { get; set; }
        public string colTestPlanUrl { get; set; }
        public string colDevelopmentOfficer { get; set; }
        public string colManager { get; set; }
        public Nullable<int> colUploadBy { get; set; }
        public Nullable<System.DateTime> colUploadDt { get; set; }
        public Nullable<System.DateTime> colActiveDt { get; set; }
        public Nullable<bool> colSt { get; set; }
        public Nullable<System.DateTime> colEndDt { get; set; }
        public string colTheoryId { get; set; }
    }
}
