//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrade
    {
        public int colTradeId { get; set; }
        public string colTradeCode { get; set; }
        public string colTradeName { get; set; }
        public int colCategoryId { get; set; }
        public string colAbbreviation { get; set; }
        public bool colSt { get; set; }
        public string colChineseTradeName { get; set; }
        public string colThaiTradeName { get; set; }
        public string colTamilTradeName { get; set; }
        public string colKoreanTradeName { get; set; }
    }
}
